version: "3.9"

services:
  leagueify-server:
    container_name: leagueify-server-dev
    image: leagueify-server
    build:
      context: .
    environment:
      DATABASE_URI: postgresql://leagueify:password@leagueify-database-dev:5432/leagueify?schema=public
      PUBLIC_SENTRY: false
    volumes:
      - ./:/usr/src/app

  leagueify-database:
    container_name: leagueify-database-dev
    ports:
      - 5432:5432
