# syntax=docker/dockerfile:1

# Download Go dependencies
FROM golang:1.22.0-alpine3.19 as server-base-dev
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
RUN go install github.com/cosmtrek/air@latest

# Build Leagueify-API executable
FROM golang:1.22.0-alpine3.19 as server-builder-dev
COPY --from=server-base-dev /go/bin /go/bin
COPY --from=server-base-dev /go/pkg /go/pkg
WORKDIR /app
COPY . ./
CMD ["air", "--build.include_file", "openapi.yaml"]
