version: "3.9"

services:
  leagueify-server:
    container_name: leagueify-server-dev
    image: leagueify-server
    build:
      context: .
      dockerfile: dockerfile-dev
    volumes:
      - ./:/app

  leagueify-database:
    ports:
      - 5432:5432
