name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      leagueify-database:
        image: mongo:7.0.3
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
          MONGO_INITDB_DATABASE: leagueify-server
        ports:
          - 27017:27017

    steps:
      - name: Checkout Leagueify Server Repo
        uses: actions/checkout@v4

      - name: Prepare Bun Environment
        uses: oven-sh/setup-bun@v1

      - name: Install Leagueify Server Dependencies
        run: bun install

      - name: Generate .env
        run: echo "DATABASE_URI=mongodb://root:example@localhost:27017/leagueify-server?authSource=admin" > .env

      - name: Run Leagueify Server Tests
        run: bun test
