name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Leagueify Server Repo
        uses: actions/checkout@v4

      - name: Prepare Bun Environment
        uses: oven-sh/setup-bun@v1

      - name: Install Leagueify Server Dependencies
        run: bun install

      - name: Run Leagueify Server Tests
        run: bun test
